# Generated by Django 4.2.23 on 2025-06-26 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="title",
            field=models.CharField(default="hello", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="userquestionstatus",
            unique_together={("user", "question")},
        ),
    ]
