# Generated by Django 4.2.22 on 2025-06-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_topic_title_alter_userquestionstatus_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="title",
        ),
    ]
