# Generated by Django 4.2.23 on 2025-06-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0002_topic_title_alter_userquestionstatus_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("constraints", models.TextField(blank=True, null=True)),
                ("sample_input", models.TextField(blank=True, null=True)),
                ("sample_output", models.TextField(blank=True, null=True)),
                ("Explanation", models.TextField(blank=True, null=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="dashboard.topic",
                    ),
                ),
            ],
        ),
    ]
