# Generated by Django 4.2.22 on 2025-06-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_topic_title_alter_userquestionstatus_unique_together"),
        ("problem_detail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prob_title",
                to="dashboard.question",
            ),
        ),
    ]
