# Generated by Django 4.2.22 on 2025-06-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_topic_title"),
        ("problem_detail", "0003_testcase_delete_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testcase",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="level",
                to="dashboard.question",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic",
                to="dashboard.topic",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="name",
                to="dashboard.question",
            ),
        ),
    ]
