# Generated by Django 4.2.22 on 2025-06-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_topic_title"),
        ("problem_detail", "0004_testcase_description_testcase_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                choices=[("Easy", "Easy"), ("Med.", "Medium"), ("Hard", "Hard")],
                max_length=10,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="level",
                to="dashboard.question",
            ),
        ),
    ]
