# Generated by Django 4.2.22 on 2025-06-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem_detail", "0005_alter_testcase_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("Easy", "Easy"), ("Med.", "Medium"), ("Hard", "Hard")],
                max_length=10,
                null=True,
            ),
        ),
    ]
