# Generated by Django 4.2.22 on 2025-06-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem_detail", "0006_alter_testcase_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="constraints",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testcase",
            name="explanations",
            field=models.TextField(blank=True, null=True),
        ),
    ]
