# Generated by Django 4.2.23 on 2025-07-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem_detail", "0007_testcase_constraints_testcase_explanations"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="hidden_input_file",
            field=models.FileField(
                blank=True,
                help_text="Optional: File with hidden test cases",
                null=True,
                upload_to="testcases/hidden_inputs/",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="hidden_output_file",
            field=models.FileField(
                blank=True,
                help_text="Optional: Corresponding hidden outputs",
                null=True,
                upload_to="testcases/hidden_outputs/",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="input_file",
            field=models.FileField(
                help_text="File with visible test cases, separated by '---'",
                upload_to="testcases/inputs/",
            ),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="output_file",
            field=models.FileField(
                help_text="File with corresponding visible outputs",
                upload_to="testcases/outputs/",
            ),
        ),
    ]
