# Generated by Django 4.2.23 on 2025-07-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem_detail", "0009_codesubmission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CodeSubmission",
        ),
    ]
