# Generated by Django 4.2.23 on 2025-07-10 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0004_usersolvedquestion_delete_userquestionstatus"),
        ("compile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="codesubmission",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.question",
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="codesubmission",
            name="verdict",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
